
DE_PARA_SOURCE = {
    'Bulgarian': 'Búlgaro',
    'Czech': 'Tcheco',
    'Danish': 'Dinamarquês',
    'German': 'Alemão',
    'Greek': 'Grego',
    'English (British)': 'Inglês (Britânico)',
    'English (American)': 'Inglês (Americano)',
    'Spanish': 'Espanhol',
    'Estonian': 'Estoniano',
    'Finnish': 'Finlandês',
    'French': 'Francês',
    'Hungarian': 'Húngaro',
    'Indonesian': 'Indonésio',
    'Italian': 'Italiano',
    'Japanese': 'Japonês',
    'Korean': 'Coreano',
    'Lithuanian': 'Lituano',
    'Latvian': 'Letão',
    'Norwegian': 'Norueguês',
    'Dutch': 'Holandês',
    'Polish': 'Polonês',
    'Portuguese (Brazilian)': 'Português (Brasileiro)',
    'Portuguese (European)': 'Português (Europeu)',
    'Romanian': 'Romeno',
    'Russian': 'Russo',
    'Slovak': 'Eslovaco',
    'Slovenian': 'Esloveno',
    'Swedish': 'Sueco',
    'Turkish': 'Turco',
    'Ukrainian': 'Ucraniano',
    'Chinese (simplified)': 'Chinês (simplificado)',
}

DE_PARA_TARGET = {
    'Bulgarian': 'Búlgaro',
    'Czech': 'Tcheco',
    'Danish': 'Dinamarquês',
    'German': 'Alemão',
    'Greek': 'Grego',
    'English': 'Inglês',
    'Spanish': 'Espanhol',
    'Estonian': 'Estoniano',
    'Finnish': 'Finlandês',
    'French': 'Francês',
    'Hungarian': 'Húngaro',
    'Indonesian': 'Indonésio',
    'Italian': 'Italiano',
    'Japanese': 'Japonês',
    'Korean': 'Coreano',
    'Lithuanian': 'Lituano',
    'Latvian': 'Letão',
    'Norwegian': 'Norueguês',
    'Dutch': 'Holandês',
    'Polish': 'Polonês',
    'Portuguese': 'Português',
    'Romanian': 'Romeno',
    'Russian': 'Russo',
    'Slovak': 'Eslovaco',
    'Slovenian': 'Esloveno',
    'Swedish': 'Sueco',
    'Turkish': 'Turco',
    'Ukrainian': 'Ucraniano',
    'Chinese': 'Chinês',
}

