
DE_PARA_TARGET = {
    'Búlgaro': 'Bulgarian',
    'Tcheco': 'Czech',
    'Dinamarquês': 'Danish',
    'Alemão': 'German',
    'Grego': 'Greek',
    'Inglês (Britânico)': 'English (British)',
    'Inglês (Americano)': 'English (American)',
    'Espanhol': 'Spanish',
    'Estoniano': 'Estonian',
    'Finlandês': 'Finnish',
    'Francês': 'French',
    'Húngaro': 'Hungarian',
    'Indonésio': 'Indonesian',
    'Italiano': 'Italian',
    'Japonês': 'Japanese',
    'Coreano': 'Korean',
    'Lituano': 'Lithuanian',
    'Letão': 'Latvian',
    'Norueguês': 'Norwegian',
    'Holandês': 'Dutch',
    'Polonês': 'Polish',
    'Português (Brasileiro)': 'Portuguese (Brazilian)',
    'Português (Europeu)': 'Portuguese (European)',
    'Romeno': 'Romanian',
    'Russo': 'Russian',
    'Eslovaco': 'Slovak',
    'Esloveno': 'Slovenian',
    'Sueco': 'Swedish',
    'Turco': 'Turkish',
    'Ucraniano': 'Ukrainian',
    'Chinês (simplificado)': 'Chinese (simplified)',
}

DE_PARA_SOURCE = {
    'Búlgaro': 'Bulgarian',
    'Tcheco': 'Czech',
    'Dinamarquês': 'Danish',
    'Alemão': 'German',
    'Grego': 'Greek',
    'Inglês': 'English',
    'Espanhol': 'Spanish',
    'Estoniano': 'Estonian',
    'Finlandês': 'Finnish',
    'Francês': 'French',
    'Húngaro': 'Hungarian',
    'Indonésio': 'Indonesian',
    'Italiano': 'Italian',
    'Japonês': 'Japanese',
    'Coreano': 'Korean',
    'Lituano': 'Lithuanian',
    'Letão': 'Latvian',
    'Norueguês': 'Norwegian',
    'Holandês': 'Dutch',
    'Polonês': 'Polish',
    'Português': 'Portuguese',
    'Romeno': 'Romanian',
    'Russo': 'Russian',
    'Eslovaco': 'Slovak',
    'Esloveno': 'Slovenian',
    'Sueco': 'Swedish',
    'Turco': 'Turkish',
    'Ucraniano': 'Ukrainian',
    'Chinês': 'Chinese',
}